### ISSUE TITLE
graphql_ppx => graphql-ppx

### ISSUE THREAD

**Issue by jfrolich** [reasonml-community/graphql-ppx#113]
The convention seems to be to use a dash in the name of ppx's. The underscore in the current name is a bit awkward. A dash works better almost in any context. Any opinions here?

Perhaps we can change the repo name at least (no real downsides). And change the npm package name when we move it to the `reasonml-community` context.

**Comment by Et7f3** [comment]
On opam we see more underscored package. And ppx_ at the beginning so when we search we could easily spot wich package has a ppx associated.
7 have _ppx at the end
6 have -ppx at the end (One jsoo have -ppx_deriving_json)
1 one have ppx-
Near one hundred have ppx_

**Comment by jfrolich** [comment]
I think it is more common on OCaml to use `ppx_<name>` and on Reason it looks like its more common to have `<name>-ppx`. Given that we mainly target Reason I prefer going for graphql-ppx.

**Comment by jfrolich** [comment]
After some discussion it looks like we landed on `@reasonml-community/graphql-ppx` (on NPM) for 1.0.
