### ISSUE TITLE
Bug with multiple queries when passing arguments to both queries

### ISSUE THREAD

**Issue by lessp** [reasonml-community/graphql-ppx#145]
Hey all, thanks for your hard work on the library.

I'm getting an error with the following query in Gatsby with the `graphql_ppx_re` version `1.0.0-beta.9`:
```
query MyQuery {
  code: allMarkdownRemark(filter: {fileAbsolutePath: {regex: "/code/"}}) {
    edges {
      node {
        id
        html
        frontmatter {
          title
        }
      }
    }
  }
  
  usps: allMarkdownRemark(filter: {fileAbsolutePath: {regex: "/usps/"}}, sort: {fields: [frontmatter___order], order: ASC}) {
    edges {
      node {
        id
        html
        frontmatter {
          title
          description
          emoji
        }
      }
    }
  }
}
```
The query works in GraphiQL, but within Reason I'm hit with the following error:
```
[1/3] Building src/pages/index.reast
FAILED: src/pages/index.reast 
/Users/ter/dev/diverse/reason/gatsby-site-reason/node_modules/bs-platform/darwin/bsc.exe  -w -30 -color always -bs-jsx 3 -ppx '/Users/ter/dev/diverse/reason/gatsby-site-reason/node_modules/@dylanirlbeck/tailwind-ppx/tailwind-ppx -path ./src/styles/tailwind.css' -ppx '/Users/ter/dev/diverse/reason/gatsby-site-reason/node_modules/@baransu/graphql_ppx_re/ppx -records -template-tag-import=graphql -template-tag-location=gatsby' -open Tablecloth -o src/pages/index.reast -bs-syntax-only -bs-binary-ast /Users/ter/dev/diverse/reason/gatsby-site-reason/src/pages/index.re
Fatal error: exception Invalid_argument("Bytes.create")

  We've found a bug for you!
  /Users/ter/dev/diverse/reason/gatsby-site-reason/src/pages/index.re
  
  Error while running external preprocessor
Command line: /Users/ter/dev/diverse/reason/gatsby-site-reason/node_modules/@baransu/graphql_ppx_re/ppx -records -template-tag-import=graphql -template-tag-location=gatsby '/var/folders/t9/_tgk7jdn0lddhyhykg1kpq8r0000gp/T/camlppx5a9792' '/var/folders/t9/_tgk7jdn0lddhyhykg1kpq8r0000gp/T/camlppxb95905'

  
FAILED: subcommand failed.
>>>> Finish compiling(exit: 1)
```

Removing the filter from one of the queries allows it to work properly, in other words:
```
query MyQuery {
  code: allMarkdownRemark {
    ...
  }
  
  usps: allMarkdownRemark(filter: {fileAbsolutePath: {regex: "/usps/"}}, sort: {fields: [frontmatter___order], order: ASC}) {
    ...
  }
}
```

Does work!

**Comment by vmarcosp** [comment]
The same here :(

**Comment by jfrolich** [comment]
@jsiebern any idea?

**Comment by jsiebern** [comment]
Nah, but I'll have one. I'll check it out tomorrow :)

**Comment by jsiebern** [comment]
@lessp Could you provide me with a schema file to reproduce please? I'm struggling to re-create the error

**Comment by jfrolich** [comment]
Here a generic gatsby schema: 
[graphql_schema.json.zip](https://github.com/reasonml-community/graphql-ppx/files/4856377/graphql_schema.json.zip)

**Comment by lessp** [comment]
> @lessp Could you provide me with a schema file to reproduce please? I'm struggling to re-create the error

Let me know if what @jfrolich provided you doesn't work, otherwise I can throw together a basic project setup. 🙂

**Comment by jsiebern** [comment]
@lessp Yes please, the schema by @jfrolich actually works with your original posted query (except complaining that `ASC` should be an array & `emoji` doesn't exist. Probably a Gatsby plugin thing?

**Comment by lessp** [comment]
> @lessp Yes please, the schema by @jfrolich actually works with your original posted query (except complaining that `ASC` should be an array & `emoji` doesn't exist. Probably a Gatsby plugin thing?

See if this breaks @jsiebern, https://github.com/lessp/graphql_ppx_reproduce

In `BlogPost.re`, changing:

```
    foo: markdownRemark(fields: { slug: { eq: $slug } }) {
```

to:

```
    foo: markdownRemark {
```

works for me. Made this very quickly, so might have missed something else!

**Comment by jsiebern** [comment]
Ah, got it, it only breaks with `-template-tag=graphql` added. Thanks for the repro!

**Comment by jsiebern** [comment]
Can you try with the current master? I was just looking into this and found that the current master works with the repro. Probably a template-tag change that @jfrolich introduced?

**Comment by johnridesabike** [comment]
I haven’t run into this bug since upgrading to beta 18.

**Comment by jfrolich** [comment]
Yes it was my bug in the pretty printer (only used for template tags)
