### ISSUE TITLE
Gatsby only allows one query per file.

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#146]
Reproduced on 1.0.0-beta.9.

This may be mainly a documentation issue, but if there’s a way that the PPX can play nicely with Gatsby by default then that would be great.

A query like this is valid, but the PPX doesn’t compile it in a way that is compatible with Gatsby:
```graphql
fragment ImageFluid on ImageSharpFluid {
  srcSet
  src
  sizes
  aspectRatio
}

query PageByPath($path: String!) {
  markdownRemark(fields: {fullPath: {eq: $path}}) {
    frontmatter {
      thumbnail {
        image {
          sharpImg: childImageSharp {
            mobileImage: fluid(maxWidth: 600) {
              ...ImageFluid
            }
            desktopImage: fluid(maxWidth: 1200) {
              ...ImageFluid
            }
          }
        }
      }
    }
  }
}
```

The problem is that the PPX will create two query modules, one for `ImageFluid` and one for `PageByPath`. Gatsby only allows one “root” query per JS file. 

This also fails because the PPX will re-import Gatsby’s `graphql` value (`let { graphql } = require("gatsby”)`) for every query, and the Gatsby compiler doesn’t allow `graphql` to be redefined after it’s been imported.

**Workaround:** In order to use the `ImageFluid` fragment, it has to be extracted to its own file.

**Comment by jfrolich** [comment]
Yes. The previous approach of utilizing the template string didn't allow more than one queries. I found another approach that works with Gatsby. Should be resolved in Beta 10. (Building now)

**Comment by johnridesabike** [comment]
What should be the expected behavior now? When I  put multiple queries in one file with beta 11 I get the same errors.

**Comment by jfrolich** [comment]
Fixed
