### ISSUE TITLE
Gatsby doesn’t recognize queries that aren’t directly exported

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#147]
Reproduced on 1.0.0-beta.9.

Say you have a file with this code:

```reason
// Title.re
[%graphql {|
query Title {
  markdownRemark {
    frontmatter {
      title
    }
  }
}
|}];
```

Gatsby will not recognize this query because the query value is not directly exported. The module `Title` is exported (which contains `Title.query`) but Gatsby’s compiler doesn’t recognize that.

**Workaround:** Exporting the query directly with `{inline: true}`, `let query = Title.query`, or removing the query name `Title ` seems to fix this.

This may be mainly a documentation issue, but if the PPX is able to play nicely with Gatsby by default then that would be good.

**Comment by jfrolich** [comment]
Yes, indeed. This needs to be documented. As far as I know this is the only way to achieve it.

**Comment by jfrolich** [comment]
Unfortunately this is how gatsby works
