### ISSUE TITLE
Inlining a fragment query doesn’t compile correctly when the fragment is used

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#148]
Reproduced on 1.0.0-beta.9.

Say you have two files:

```reason
// Test_Frag.re
[%graphql
  {|
fragment ImageFluidFragment on ImageSharpFluid {
  srcSet
  src
  sizes
  aspectRatio
}
|};
  {inline: true}
];
```

```reason
// Test.re
[%graphql
  {|
query Test($path: String!) {
  markdownRemark(fields: {fullPath: {eq: $path}}) {
    frontmatter {
      thumbnail {
        image {
          sharpImg: childImageSharp {
            mobileImage: fluid(maxWidth: 600) {
              ...Test_Frag
            }
            desktopImage: fluid(maxWidth: 1200) {
              ...Test_Frag
            }
          }
        }
      }
    }
  }
}
|}
];
```

When the PPX compiles this, the JS output still has `Test_Frag` in the query, not the actual name of the fragment (`ImageFluidFragment`).

It seems that `{inline: true}` makes the PPX believe that the fragment’s name is the same as its module name. 

`{inline: true}` can be handy to work around #147 in Gatsby.

**Expected behavior:** The PPX should either compile `Test_Frag` (the module name) to `ImageFluidFragment` (the fragment name), or it should accept `ImageFluidFragment` in the query and recognize which Reason module it’s coming from.

**Comment by jfrolich** [comment]
Strange! I did some testing and I don't see this. Can you try to reproduce this in a test query? It should call `Test_Frag.name` as the fragment name, and `Test_Frag.query` as the query that is included.

**Comment by johnridesabike** [comment]
I set up an example repo.

Fragment A, not inline, works: https://github.com/johnridesabike/gql-ppx-test/blob/master/src/Query_Frag_A.re

Fragment B, inline, doesn’t work: https://github.com/johnridesabike/gql-ppx-test/blob/master/src/Query_Frag_B.re

Query using the fragments: https://github.com/johnridesabike/gql-ppx-test/blob/master/src/Query.re

And the JS output: https://github.com/johnridesabike/gql-ppx-test/blob/master/src/Query.bs.js

The output uses the Reason module name where the fragment name should be in fragment B.

**Comment by jeddeloh** [comment]
Looks like you're using template tags. Possibly related? https://github.com/reasonml-community/graphql-ppx/issues/160

**Comment by jfrolich** [comment]
Noted, will fix!

**Comment by jfrolich** [comment]
Should be resolved now!
