### ISSUE TITLE
Ignore unused values

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#149]
If you write a query to be used inside a React component, and use an interface file to *only* export the component, then you get a lot of warnings/errors for unused values.

Example:
```
  Warning number 32 (configured as error)
  (No file name)

  unused value makeDefaultVariables.

  Warning number 32 (configured as error)
  (No file name)

  unused value graphql_module.
```

This has to be fixed by either exporting the values or explicitly ignoring them

```reason
let _ = makeDefaultVariables;
let _ = Z__INTERNAL.graphql_module;
```

Although that workaround exists, it’s not an ideal user experience, and it leaks implementation details. It would be good if the PPX could tell the compiler to ignore potentially-unused values by default.

Tested with 1.0.0-beta.10.

**Comment by jfrolich** [comment]
That would be great. Any idea if such an annotation exists?

**Comment by jfrolich** [comment]
The plan is for `Z__INTERNAL` to not be generated when `NODE_ENV` is set to production.

**Comment by jfrolich** [comment]
But for the rest, it can or cannot be used. We don't really know that inside of the PPX.

**Comment by johnridesabike** [comment]
Would prefixing the values with `_` work? AFAIK that’s the usual way to ignore values, e.g. `_graphql_module`.

**Comment by johnridesabike** [comment]
> The plan is for `Z__INTERNAL` to not be generated when `NODE_ENV` is set to production.

This would probably cause additional problems if users have to manually ignore or export it themselves, since their development code wouldn’t be compatible with the production build. 

IMO, requiring the user to manually handle values like `makeDefaultVariables` isn’t necessarily a problem since that’s part of the public API anyway, but the internal stuff seems like a real issue. I think the solution would be to prefix everything internal with an underscore.

**Comment by jfrolich** [comment]
> Would prefixing the values with `_` work? AFAIK that’s the usual way to ignore values, e.g. `_graphql_module`.

Of course, great idea! The internal values are purely for aiding hover information for the language server.

**Comment by jfrolich** [comment]
BTW I added: https://github.com/reasonml-community/graphql-ppx/commit/f746c80cce1772479a0608f21c54d3af5ad31beb. This shouldn't raise warning 32 in the definition module again (as you can't edit it). I think this is the best solution.

**Comment by vasco3** [comment]
hi, I'm using `1.0.0-beta.2` and getting a similar error

```
Warning number 32 (configured as error) 
[0]   (No file name)
[0]   
[0]   unused value definition.
```
I wonder if it is related to GraphQL_ppx

**Comment by vasco3** [comment]
I fixed with adding this to my .rei
```
module Mutation: {
  type t;
  let definition: (
    Js.Json.t => t,
    string,
    (~f: Js.Json.t => 'a, ~quoteId: string, ~internalNote: string, unit) => 'a,
  );
};
```

**Comment by jfrolich** [comment]
This is fixed in the latest beta (but a lot of breaking changes since beta 2!)

**Comment by vasco3** [comment]
yeah I can see the breaking changes. I would like to be able to use the variablesToJson method but seems like it isn't available in beta 18. Am I correct?
