### ISSUE TITLE
Support graphql sdl schemas

### ISSUE THREAD

**Issue by amiralies** [reasonml-community/graphql-ppx#150]
Json schemas are not human friendly. having `.graphql` schemas in repository  can be helpful

**Comment by jfrolich** [comment]
Happy to accept a PR for this

**Comment by baransu** [comment]
It's also good pattern to update `.graphql` schema first (when the backend is in progress and there is no possibility to use introspection query) and write based on that graphql queries. It allows you to have a solid communication interface even when implementation is not ready

**Comment by baransu** [comment]
My workflow  relies on third-party libraries to generate JSON schema from `graphql` file. I'm not sure if it's crucial to include it into graphql_ppx itself but this reduces number of files you have.

**Comment by jfrolich** [comment]
Yes if you already have a `.graphql` it's much easier if the library is able to parse that. It's also a more readable representation so better to check it into source control than the JSON file.

**Comment by jfrolich** [comment]
It's in master now! 🚀
