### ISSUE TITLE
Ability to configure template tag per query

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#152]
In 1.0.0-beta.10, the way you configure a template tag is like this:

```json
{
  "ppx-flags": [
    [
      "@baransu/graphql_ppx_re/ppx",
      "-template-tag-import=graphql",
      "-template-tag-location=gatsby"
    ]
  ]
}
```

This will print the `graphql` template tag any time the `[%graphql]` PPX is used. The problem (at least in Gatsby) is that its [Node API](https://www.gatsbyjs.org/docs/node-apis/) doesn’t use that template tag, it just accepts queries through regular strings.

For the case of Gatsby, I think it makes sense to use the template tag by default but be able to disable it when needed. Perhaps an option like `[%graphql {|...|}; {template_tag: None}];` would work?

**Comment by jfrolich** [comment]
Yes you can do that already, just use camel-case for the options per query!

`templateTagLocation`, `templateTagImport` and `taggedTemplate` are available there.

use `taggedTemplate: false` to not have a tagged template literal.

**Comment by jfrolich** [comment]
Good one to have in the documentation :)

**Comment by johnridesabike** [comment]
Thanks! That’s awesome that it’s already exists. Definitely would be good to have documented.

**Comment by jfrolich** [comment]
Ah I see I only tested a possible solution with Relay (and I think Gatsby), but I did not implement it yet. Can you try out the `851011e` dev release. This adds an inline require, so it does not collide (building now).

**Comment by jfrolich** [comment]
If if the gatsby babel plugin does not work with it you can just use template tag as `graphql` (and no import or location) then it doesn't `require` anything. The babel plugin will strip this out anyway. Then we should PR Gatsby to support this syntax.

**Comment by jfrolich** [comment]
Fixed
