### ISSUE TITLE
PPX in interface files

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#157]
Unless I’m missing something, it doesn’t seem to be possible to use the `[%graphql]` PPX in `.rei`files. This causes `Error: Syntax error` in the compiler:

```reason
/* Query.re */
[%graphql {|
  query ExampleQuery {
    myQuery {
      myField
    }
  }
|}];
```

```reason
/* Query.rei */
[%graphql {|
  query ExampleQuery {
    myQuery {
      myField
    }
  }
|}];
```

If this was possible, it would be very convenient. It would also partially help with #149 since users could easily export all of the generated types and values.

**Comment by jfrolich** [comment]
No this is not possible but doesn't this create unnecessary repetition? You can add the generated module and the parts of the generated module that you'd like to export in the rei. You can also add a typical general module type.

```
/* Query.rei */
module ExampleQuery: GraphQL_PPX.Definition;
```

**Comment by johnridesabike** [comment]
I just tried that (in beta 11), but I’m getting an `Unbound module type GraphQL_PPX.Definition` error. When I inspect the module type of `GraphQL_PPX`, this is what it prints:

```reason
{ let deepMerge: (Js.Json.t, Js.Json.t) => Js.Json.t; }
```

Using the module type definition would be handy, but it wouldn’t be able to export the different record definitions, just the `t` types and the functions, correct?

If the PPX was usable in interfaces, then it would create repetition in the sense that you need to write (or copy/paste) the query in two places. But, if you want to export the types with an interface file, you’ll still need to manually write the types generated by the PPX, and keep them in sync if the schema or if the query changes. IMO copying the query is the preferable option, if it’s possible.

This may be an apples-to-oranges comparison, but I’m thinking of how other PPXes can work in interface files:

```reason
/* Component.re */
[@react.component]
let make = () => <div />
```
```reason
/* Component.rei */
[@react.component]
let make: unit => React.element;
```

I think that’s preferable compared to hand-writing the definitions for `makeProps` etc. in the interface.

**Comment by jfrolich** [comment]
`GraphQL_PPX` doesn't ship interface files (yet). It was just an example.

Usually you only want to share parts of the module with other modules right (if you'd like to share everything, you can do that by not having a definition file.

I don't know if the `[@react.component]` annotation is a good example because it generates two similar functions `make` and `makeProps`. 

We can definitely make the `%graphql` extension point work in definition files, but now you have the same query in two places. And you have the same effect as not having an definition file.

If for instance you'd want to share the parts of the query that are used by Apollo, so you can use it in `useQuery`, the following definition would work:

```reason
/* Query.rei */
module ExampleQuery: ApolloClient.Types.Operation;
```

Isn't that nicer than repeating the whole query?

**Comment by johnridesabike** [comment]
> And you have the same effect as not having an definition file.

A more practical situation is when you already are using an interface to expose parts of your module, and then you want to also add a GraphQL query to the module. 

> Isn't that nicer than repeating the whole query?

Indeed, I agree this approach would be preferable in many (most?) situations.

Either way, I think this feature would be more “nice to have” than “necessary.”

**Comment by jfrolich** [comment]
I think that this would actually be neat if you want to share record types and have a `rei` file. I can detect that we are in an interface file in the ppx and turn on a flag to not generate implementations.

**Comment by jfrolich** [comment]
Ok. Since we recently added support for generating signatures. Allowing the `%graphql` extension point in interfaces was a smaller step to add. It just landed in master!
