### ISSUE TITLE
Modules not extended when {inline: true}

### ISSUE THREAD

**Issue by jeddeloh** [reasonml-community/graphql-ppx#161]
Pretty much what the title says :) `{inline: true}` Modules don't get extended. I'm on `v1.0.0-beta.12`, fwiw.

**Comment by jfrolich** [comment]
Yes. We have to refactor how extension works. I think it will be possible to add this functionality.

**Comment by jeddeloh** [comment]
Cool. For now I'll just add instructions not to do that for reason-apollo-client.

**Comment by jfrolich** [comment]
Resolved!
