### ISSUE TITLE
Interface-returning query not compiling

### ISSUE THREAD

**Issue by amsross** [reasonml-community/graphql-ppx#168]
A query that returns an interface does not compile.

Here are the versions in play:
```
node@12.16.1
npm@6.13.4
bs-platform@7.3.2
@reasonml-community/graphql-ppx@1.0.0-beta.17
```

Here is the error:
```
  This type constructor's parameter, `t_sport_SportBase`, can't be found. Is it a typo?
```

Here is the query:
```
[%graphql
  {|
    query {
      sport {
        name
        ... on Football { yards }
      }
    }
  |}
];
```

And here is a simple schema against which this issue arises:
```
interface SportBase {
  name: String!
}

type Football implements SportBase {
  name: String!
  yards: Int
}

type Query {
  sport: SportBase
}
```

**Comment by amsross** [comment]
Here's a REPL showing the code necessary to run that server: https://repl.it/@amsross/graphql-interface-query#index.js

**Comment by anmonteiro** [comment]
duplicate of https://github.com/reasonml-community/graphql-ppx/issues/92 ?

**Comment by amsross** [comment]
@anmonteiro I saw that issue, but wasn't sure if it was related. I'll close this and follow that one. Thanks!

**Comment by jfrolich** [comment]
Yes. This is not implemented yet (I think the only part of the spec we haven't covered?). Would be great to have this but it will probably land in 1.1 after we release 1.0.
