### ISSUE TITLE
Gatsby + beta.18:  "String interpolation is not allowed in graphql tag"

### ISSUE THREAD

**Issue by vmarcosp** [reasonml-community/graphql-ppx#169]
Updated my gatsby project from beta.12 to beta.18 and a I got a message like this:
```
String interpolation is not allowed in graphql tag:
  29 |     }
  30 |   }
> 31 |   ${frag_0}
     |  ^^^^^^^^^
  32 | `)($$Image.Fragments.GatsbyImageSharpFluid.query);
  33 | 
  34 | function parse(value) {
```
I'm using graphql fragments and it was working with beta.12.

**Comment by jfrolich** [comment]
Yes you need to set "fragment-in-query=exclude". I didn't take the time to document this yet! Sorry!

**Comment by vmarcosp** [comment]
no problem @jfrolich! thanks :)

**Comment by jfrolich** [comment]
Template tags were hacked in before to just support Gatsby. Now we have proper support for them, this setting is necessary to make sure the fragments are not embedded in the query which is the default for `graphql-ppx`.
