### ISSUE TITLE
Upgrade path to graphql_ppx@1.0

### ISSUE THREAD

**Issue by mbirkegaard** [reasonml-community/graphql-ppx#187]
We're looking very much forward to upgrading to 1.0. The new version is shaping up nicely!

We're currently using `@baransu/graphql_ppx_re@0.6.4" (and latest version of `reason-apollo-hooks` but well not worry about that for now).

When installing `@reasonml-community/graphql-ppx@next` (and the 1.0 compatible version of reason-apollo-hooks) we, as would be expected, get a whole bunch of compile errors. 

Firstly, there's the `ppxDecoder must be given 'module' argument` error. I would have expected that just naively search-replacing `@bsDecoder(fn: )` with `@bsDecoder(module: ` to not work, but what I'm seeing is now a `ppxDecoder must be given 'fn' argument` error. Do we have to supply both?

Secondly, is there (going to be) a way for us to incrementally adopt 1.0? We have 317 usages of @bsDecoder and 164 usages of @bsRecord. Some amount of the decoders expect an object, not a record. Rewriting all of this in one go is going to be a very daunting task. Is there a backwards-compatibility mode? Do you have any advice on how to approach a rewrite?

**Comment by mbirkegaard** [comment]
> Firstly, there's the `ppxDecoder must be given 'module' argument` error. I would have expected that just naively search-replacing `@bsDecoder(fn: )` with `@bsDecoder(module: ` to not work, but what I'm seeing is now a `ppxDecoder must be given 'fn' argument` error. Do we have to supply both?

Aha! `@bsDecoder` on fragments wants `fn`. `@bsDecoder` on fields and queries wants `module`. How does adding a `@bsLegacyDecoder` (or `@ppxLegacyDecoder`) directive sound? Or making `@bsDecoder` and `@ppxDecoder` behave differently? The former wants `fn`, the latter wants `module`.

**Comment by mbirkegaard** [comment]
> Firstly, there's the `ppxDecoder must be given 'module' argument` error. I would have expected that just naively search-replacing `@bsDecoder(fn: )` with `@bsDecoder(module: ` to not work, but what I'm seeing is now a `ppxDecoder must be given 'fn' argument` error. Do we have to supply both?

Aha! @bsDecoder on fragments wants fn. @bsDecoder on fields and queries wants module. How does adding a @bsLegacyDecoder (or @ppxLegacyDecoder) directive sound? Or making @bsDecoder and @ppxDecoder behave differently? The former wants fn, the latter wants module.

**Comment by jfrolich** [comment]
> Firstly, there's the ppxDecoder must be given 'module' argument error. I would have expected that just naively search-replacing @bsDecoder(fn: ) with @bsDecoder(module: to not work, but what I'm seeing is now a ppxDecoder must be given 'fn' argument error. Do we have to supply both

Thanks for discovering. There was still a `ppxCustom`/`ppxDecoder` that would accept an `fn` instead of `module` on a fragment. This is fixed in master (building now), there should be a dev release when it finished building.

**Comment by jfrolich** [comment]
> Secondly, is there (going to be) a way for us to incrementally adopt 1.0? We have 317 usages of @bsDecoder and 164 usages of @bsRecord. Some amount of the decoders expect an object, not a record. Rewriting all of this in one go is going to be a very daunting task. Is there a backwards-compatibility mode? Do you have any advice on how to approach a rewrite?

I tried to work on a migration path. But because so much changed there is some refactoring work necessary to adopt 1.0. This becomes even trickier because the clients that adopt `graphql-ppx` also have a different API (due to the architecture clients can be much more typesafe, but this also changes the API).

Steps you can take:

##  Use the `objects` switch and incrementally adopt records

This will make the migration a bit easier.

## Remove all instances of `bsRecord`

GraphQL ppx is now generating these types automatically, so you can basically strip them all out.

## `bsDecoder` to `ppxCustom`

You have to create modules with `t`, `parse` and `serialize` for these instances. I am open to a PR to change the behavior of `bsDecoder` to accept a function. The complexity here is that we cannot serialize it anymore.

**Comment by mbirkegaard** [comment]
Thank you for the quick reply! I'll think about what a `@bsDecoderUnsafe` could look. That it can't automatically serialize is not a problem (could just throw an exception if the serialize function is called) it would only be for backwards compatibility (where we can't serialize either).

**Comment by mbirkegaard** [comment]
I don't think there's a good way forward here. It might be easier to simultaneously use two separate versions of the ppx, one old one new and migrate over one at a time. I'll close this until I have a concrete suggestion.

**Comment by Pet3ris** [comment]
> > Secondly, is there (going to be) a way for us to incrementally adopt 1.0? We have 317 usages of @bsDecoder and 164 usages of @bsRecord. Some amount of the decoders expect an object, not a record. Rewriting all of this in one go is going to be a very daunting task. Is there a backwards-compatibility mode? Do you have any advice on how to approach a rewrite?
> 
> I tried to work on a migration path. But because so much changed there is some refactoring work necessary to adopt 1.0. This becomes even trickier because the clients that adopt `graphql-ppx` also have a different API (due to the architecture clients can be much more typesafe, but this also changes the API). The reason for a big breaking release is that my thought process is that it's better to have a single painful breaking release than several smaller breaking releases. There were many features that would be breaking in the future, so that's why we have been in beta for quite a long time. The current version is on the verge of release. The API is very well thought out and I don't foresee breaking releases in the near future.
> 
> Steps you can take:
> ### Use the `objects` switch and incrementally adopt records
> 
> This will make the migration a bit easier.
> ### Remove all instances of `bsRecord`
> 
> GraphQL ppx is now generating these types automatically, so you can basically strip them all out.
> ### `bsDecoder` to `ppxCustom`
> 
> You have to create modules with `t`, `parse` and `serialize` for these instances. I am open to a PR to change the behavior of `bsDecoder` to accept a function. The complexity here is that we cannot serialize it anymore.

Wanted to follow up on this and clarify what the idiomatic usage should be. Right now I've been using `@bsRecord` for 2 reasons:

1) to reuse record types across different GraphQL queries
2) to be able to use `@decco` annotations on these records that are used in GraphQL queries

Is this something that I'd still be able to do if using the GraphQL generated types as core data structures in the application or is there perhaps a way to parse?
