### ISSUE TITLE
Version bound ocaml-migrate-parsetree <2.0.0

### ISSUE THREAD

**Issue by yawaramin** [reasonml-community/graphql-ppx#189]
Because of the recent release of ocaml-migrate-parsetree 2.0.0 with breaking changes, it's a good idea to set an upper bound of `< 2.0.0`: https://github.com/reasonml-community/graphql-ppx/blob/4ce13d4137e945400dcaec4679aaf6d620d826d5/esy.json#L11

**Comment by jfrolich** [comment]
Thanks! Is it possible to also support 2.0? Or are 1 and 2 not compatible?

**Comment by yawaramin** [comment]
According https://discordapp.com/channels/235176658175262720/235200837608144898/744611497426158000 , looks like they removed or maybe moved an existing module so that broke backward-compat. Of course since it's a major version that is allowed in SemVer, but it does look like 1 and 2 are not compatible.

**Comment by jfrolich** [comment]
Not relevant anymore since we are on ppxlib now
