### ISSUE TITLE
Support globally opened Belt?

### ISSUE THREAD

**Issue by jeddeloh** [reasonml-community/graphql-ppx#195]
Apologies for the small issues lately, but I've got another one. I'm sure it's a bad decision, but at some point we globally opened `Belt` 😅  and `serializeVariables` will use the core `Array.map` instead of `Js.Array.map` when it has an argument that is an array.  Example:
```
let rec serializeVariables: t_variables => Raw.t_variables =
  inp => {
    orderBy:
      (
        a =>
          switch (a) {
          | None => Js.Nullable.undefined
          | Some(b) =>
            Js.Nullable.return(
              (
                a =>
                  Array.map(
                    b => (a => serializeInputObjecttests_order_by(a))(b),
                    a,
                  )
              )(
                b,
              ),
            )
          }
      )(
        (inp: t_variables).orderBy,
      ),
    productionId: (a => a)((inp: t_variables).productionId),
  }
```

Now `Array.map` is the wrong one since I opened `Belt` resulting in a ppx error `This expression should not be a function, the expected type is array('a)`. Maybe it's not something `graphql-ppx` wants to support, but maybe this should be using `Js.Array.map` for consistency anyway? 🤷

**Comment by jeddeloh** [comment]
Obviously, you can get around this on a per-file basis, but it took me quite a while to realize what the issue was.

**Comment by jfrolich** [comment]
Yes this should be fixed, we shouldn't use `Pervasives`

**Comment by jfrolich** [comment]
You can test with cf7892db4023b88201e4cd183665255cccf54b07. Let me know if there are more uses of the OCaml stdlib vs `Js.x`.

**Comment by jeddeloh** [comment]
Awesome. Thanks! Tested and working for me.
