### ISSUE TITLE
@ppxConfig directive isn’t removed in compiled query

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#198]
ReScript syntax:
```
%graphql(`
  query Site @ppxConfig(taggedTemplate: false) {
    site {
      siteMetadata {
        title
        description
        siteUrl
      }
    }
  }
`)
```

Output query:
```
"query Site @ppxConfig(taggedTemplate: false) {\nsite  {\nsiteMetadata  {\ntitle  \ndescription  \nsiteUrl  \n}\n\n}\n\n}\n”,
```

The config directive correctly disables the tagged template, but since it’s still present on the output then the query isn’t able to compile (for Gatsby, in my case).

graphql-ppx version: 1.0.0

**Comment by jfrolich** [comment]
Fixed in [1.0.1](https://github.com/reasonml-community/graphql-ppx/compare/v1.0.0...v1.0.1)
