### ISSUE TITLE
PPX output not respecting bsconfig.json package-specs module setting

### ISSUE THREAD

**Issue by illusionalsagacity** [reasonml-community/graphql-ppx#199]
I was trying v1 out with `snowpack`, and `reason-apollo-client` and noticed the tag was compiling to `require("@apollo/client").gql` rather than using the import syntax. (`snowpack` only supports ES6 modules, so my app wouldn't load)

`require` is hardcoded here: https://github.com/reasonml-community/graphql-ppx/blob/master/src/bucklescript/output_bucklescript_module.re#L219

As a workaround I'm able to use:

```re
[%%raw {|import { gql } from "@apollo/client";|}]
```

In addition to disabling the `template-tag-location` and`template-tag-import` config options.

**Comment by jfrolich** [comment]
Yes this is basically a hack. We need additional features in the Bucklescript compiler to get this working properly (template tag literal support or identifier injection support).

Your solution is actually quite nice, but we cannot do this inside of the ppx automatically very easily (because it needs to be injected at the top of the file).

Basically this is what we need: https://github.com/rescript-lang/rescript-compiler/issues/4294. I've talked to @hongbo some time ago and something along these lines is planned, not sure when it will ship though.

**Comment by illusionalsagacity** [comment]
Ahh gotcha, that is a bit unfortunate. Too bad top level await isn't the most supported thing out there out of the box or it could use that in the meantime:

```js
await import("@apollo/client").then(gql => { gql`
...
`});
```

Just throwing stuff out there, not too familiar with the ppx capabilities, would it be possible to have a separate ppx e.g. `[@graphql.import]` that generates the identifier?

**Comment by jfrolich** [comment]
I think there is a way to inject the import statement at the top of every file when there is a graphql definition, but it would not in non-es6 mode. And it adds quite a bit of complexity. I think your approach of injecting it yourself in each file and use the importless template literal is probably the best approach for now until we have better compiler support to do something like this.

**Comment by illusionalsagacity** [comment]
>I  think your approach of injecting it yourself in each file and use the importless template literal is probably the best approach for now until we have better compiler support to do something like this.

True enough, it's not terrible for a workaround. If you like I am quite willing to add a note to the docs (either here or in `apollo-reason-client`) about it, just would need to know where to put it. 

>I think there is a way to inject the import statement at the top of every file when there is a graphql definition but it adds quite a bit of complexity (if you'd interested in PR-ing I would be open to the change). 

> The top level await wouldn't really work because now it's wrapped in a promise.

I can check it out and try some stuff, I have very little idea of what I'm doing though 🙃

**Comment by SkinyMonkey** [comment]
Did someone check this?

**Comment by jfrolich** [comment]
It's in the docs now: https://jeddeloh.github.io/rescript-apollo-client/docs/installation/. We need native template tag support in ReScript to be able to do more than this. So please support https://github.com/rescript-lang/rescript-compiler/issues/4294, or https://github.com/rescript-lang/rescript-compiler/issues/4070. This was raised almost 2 years ago so don't expect too much.
