### ISSUE TITLE
Option for opaque query types

### ISSUE THREAD

**Issue by johnridesabike** [reasonml-community/graphql-ppx#201]
It would be useful if queries could be given an opaque type instead of `string`

The motivation is that this would make adding type-safe extensions easier. For example:

```diff
module ExtendQuery: (M: GraphQLQuery) => {
  @bs.module("gatsby")
-  external useStaticQuery: string => M.Raw.t = "useStaticQuery"
+  external useStaticQuery: M.queryType => M.Raw.t = "useStaticQuery"
}
```

You can’t implement an opaque `query` type in the functor and redefine the query because Gatsby requires query values to be static--they can’t get passed through different functions before use.

**Comment by johnridesabike** [comment]
I just learned about the `templateTagReturnType` config option, which seems to mostly satisfy what I’m trying to do. I still think it would be useful to be able to have a unique type per module, if that’s feasible.

**Comment by jfrolich** [comment]
How do you mean a unique type per module?

**Comment by johnridesabike** [comment]
That was one of my first thoughts too, but sadly it is not possible in Gatsby. The input to `useStaticQuery` can’t be a variable (like a function argument). See https://www.gatsbyjs.com/docs/use-static-query/#known-limitations

Anyway, this suggestion is probably low-priority since `templateTagReturnType` almost completely solves my use case.

**Comment by jfrolich** [comment]
Ok, I'll close it then. It shouldn't be too hard to implement, perhaps even an "opaque" value to `templateTagReturnType`?
