### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mattdamon108** [reasonml-community/graphql-ppx#202]
Hi,

In case of having an error of `GraphQLError` from the gql api, the compiled query code throwing an error such as,

```
Uncaught TypeError: Cannot read property '__typename' of null
    at parse (Query.bs.js:27)
    at mapU (belt_Option.js:57)
    at Module.map (belt_Option.js:63)
    at Object.fromJs (ApolloClient__React_Types.bs.js:162)
    at eval (ApolloClient__React_Hooks_UseQuery.bs.js:52)
    at Module._1 (curry.js:51)
    at Module.useGuaranteedMemo1 (ApolloClient__Utils.bs.js:13)
    at useQuery (ApolloClient__React_Hooks_UseQuery.bs.js:51)
    at use (ApolloClient__React_Hooks_UseQuery.bs.js:72)
    at Module.app (curry.js:33)
```

I guess what it causes from this part of the compiled code.

```reason
module Ship = [%graphql
  {|
  query ship { shipRequests {
      id
      user_id
      species
      quantity
      created_at
    }
}
|}
];
```

```js
function parse(value) {
  var value$1 = value.shipRequests; // throwing error!
  return {
          shipRequests: {
            __typename: value$1.__typename,
            id: value$1.id,
            user_id: value$1.user_id,
            species: value$1.species,
            quantity: value$1.quantity,
            created_at: value$1.created_at
          }
        };
}
```

In this case, `Ship.use()` alwasy throwing an error. I think this forces me to use the [catching JS Exception](https://rescript-lang.org/docs/manual/v8.0.0/exception#catching-js-exceptions) which I am really not willing to use. Is there any workaround or a good way to avoid it?

**Comment by jfrolich** [comment]
Which client do you use? It's probably a client issue.

**Comment by jfrolich** [comment]
Ah from the error it looks like `reason-apollo-client`. Can you also share the schema? @jeddeloh

**Comment by jeddeloh** [comment]
Yeah, @mattdamon108, do you want to open an issue on `reason-apollo-client`? I only run data through the parse function if it's there, so this must be a case of having partial data. Coincidentally, I have a proposal out that would fix this issue: https://github.com/reasonml-community/reason-apollo-client/pull/45

In the meantime, maybe try setting your `errorPolicy` to `None` so you're not returning partial data along with errors?
```
  ApolloClient.(
    make(
      ~defaultOptions=
        DefaultOptions.make(
          ~query=
            DefaultQueryOptions.make(
              ~fetchPolicy=NetworkOnly,
              ~errorPolicy=None,
              (),
            ),
        ),
      ~cache=Cache.InMemoryCache.make(),
      ~link,
      (),
    )
  );
```

**Comment by mattdamon108** [comment]
@jfrolich here's my query and schema

```reason
module Ship = [%graphql
  {|
  query { shipRequests {
      id
      user_id
      species
      quantity
      created_at
    }
}
|}
];
```

```graphql
type Query {
  shipRequests: ship_request!
}

type ship_request {
  created_at: DateTime!
  id: Int!
  quantity: String!
  species: String!
  user_id: Int!
}

```

**Comment by mattdamon108** [comment]
@jfrolich @jeddeloh I'm still not sure to what this issue belongs to, the client.. or ppx..

According my schema, `Query.shipRequests` has a type `ship_request!`, it seems quite obvious that the `function parse` should looks like it. But, isn't it necessary to have a null checking inside?

```js
function parse(value) {
  if(!value || !value.shipRequests) return  // something like this maybe?

  var value$1 = value.shipRequests;
  return {
          shipRequests: {
            __typename: value$1.__typename,
            id: value$1.id,
            user_id: value$1.user_id,
            species: value$1.species,
            quantity: value$1.quantity,
            created_at: value$1.created_at
          }
        };
}
```

**Comment by jfrolich** [comment]
What server do you use? It looks like value.shipRequests can never be null, is it violating the protocol? Or is it null because there are some errors?

**Comment by mattdamon108** [comment]
@jfrolich I use `apollo server` with `prisma`. The case was caused by the authentication error actually

```reason
let getUser = (req: ApolloServer.request) => {
  switch req.headers.authorization {
    | Some(authorization) => {
      try {
        authorization
        ->Js.String2.replace("Bearer ", "")
        ->verify(jwtSecret)
      } catch {
        | Js.Exn.Error(e) => {
          let name = e->Js.Exn.name->Belt.Option.getWithDefault("ErrorName")
          let message = e->Js.Exn.message->Belt.Option.getWithDefault("ErrorMessage")
          raise(ApolloServer.authenticationError(name ++ ": " ++ message))
        }
      }
    }
    | None => raise(ApolloServer.authenticationError("Authentication Required"))
  }
}
```

**Comment by jfrolich** [comment]
Yes if there is an error it's probably a bug in the client (it shouldn't try to parse the data).

**Comment by mattdamon108** [comment]
@jfrolich fair enough. I open an issue in client repo. And @jeddeloh mentioned there is upcomming PR to fix this. I'll closed this issue. Thank you for your clarification and time.
