### ISSUE TITLE
Multiple graphql_schema.json

### ISSUE THREAD

**Issue by mattdamon108** [reasonml-community/graphql-ppx#204]
Hi,

Unfortunately, I am facing the cases to query to the multiple API inside one application. Is it possible to ppx using multiple graphql_schema.json? or Should I have to merge into one `graphql_schema.json`?

**Comment by baransu** [comment]
It is possible to specify which one do you need per query like this:
https://github.com/reasonml-community/graphql-ppx/blob/5b2b3d8fc93bc11500411c60e8f47c2d3d6e5859/tests_bucklescript/operations/pokedexScalars.re#L1-L11

**Comment by mattdamon108** [comment]
@baransu OMG! Thank you!

**Comment by jfrolich** [comment]
Actually the directive `@ppxConfig(schema: "pokedex_schema.json"}` is prefered now, but the trailing record still works!

**Comment by mattdamon108** [comment]
@jfrolich Thank you for your comment! 👍
