### ISSUE TITLE
Two problems with `@ppxCustom`

### ISSUE THREAD

**Issue by mbirkegaard** [reasonml-community/graphql-ppx#209]
## Problem 1: Parse errors

`@ppxCustom` as now implemented assumes that parsing can always be done successfully.  

Consider a schema where 
```
type Item {
  id: ID!
  name: String!
  hasPriceRange: Boolean!
  price: Int
  minPrice: Int
  maxPrice: Int
}
```
and our domain knowledge tells us that if `hasPriceRange` is `false`, then `price` should be non-null. If `hasPriceRange` is `true` then `minPrice` and `maxPrice` should be non-null.

The ideal definitions client side don't work with `@ppxCustom` because that wants 
```Reason
module Custom = {
  type t = someType;
  let parse: raw => t;
  let serialize: t => raw;
}
```
and thus doesn't work if parsing could fail. One could do something like;
```Reason
module Custom = {
  type t = result(someType, string);
  let parse: raw => t;
  let serialize: t => raw;
}
```
but making `serialize` accept a result is hardly ideal either.

### Proposal
A new directive, e.g. `@ppxParser`, that accepts something like
```Reason
module Custom = {
  type t;
  let parse: raw => result(t, 'error);
  let serialize: t => raw;
}
```

<details>
<summary>Full client-side implementation of Item</summary>

```Reason
type price =
  | Price(int)
  | PriceRange(int, int);

module Item = {
  type t = {
    id: string,
    name: string,
    price,
  };
};

type raw = {
  id: string,
  name: string,
  hasPriceRange: bool,
  price: option(int),
  minPrice: option(int),
  maxPrice: option(int),
};

module ItemDecoder = {
  type t = Item.t;
  let parse: raw => result(t, 'error) =
    ({id, name, hasPriceRange, price, minPrice, maxPrice} as p) =>
      switch (hasPriceRange, price, minPrice, maxPrice) {
      | (false, Some(price), _, _) => Ok({id, name, price: Price(price)})
      | (true, _, Some(minPrice), Some(maxPrice)) =>
        Ok({id, name, price: PriceRange(minPrice, maxPrice)})
      | _ => Error({j|Error parsing price: $p|j})
      };

  let serialize: t => raw =
    ({id, name, price}) => {
      switch (price) {
      | Price(price) => {
          id,
          name,
          hasPriceRange: false,
          price: Some(price),
          minPrice: None,
          maxPrice: None,
        }
      | PriceRange(minPrice, maxPrice) => {
          id,
          name,
          hasPriceRange: true,
          price: None,
          minPrice: Some(minPrice),
          maxPrice: Some(maxPrice),
        }
      };
    };
};
```
</details>

## Problem 2: Serialization isn't always possible or desired
`@ppxCustom` forces the programmer to implement `serialize`. That might be fine (if somewhat cumbersome) for small fragments and small queries, but for large top-level queries and more complicated types it will add a lot of extra work. The programmer knows from the application requirements whether they want to be able to serialize. `@ppxCustom` doesn't know, but still forces them to be able serialize. 

I can even imagine cases where it's impossible to write `serialize` or where, to make it possible, the programmer would have to write the types so that they work for serialization, instead of what is best for the application.

### Proposal
Reintroducing the old `@bsDecoder` directive as `@ppxDecoder`. It accepts a function that parses the `t_whatever` type into what the application needs, but which most often would be either `t` or `result(t, 'error)`.

This was suggested by @jfrolich in #187 as a measure to ease upgrading to 1.0, but I now think that such a directive is generally needed

**Comment by mbirkegaard** [comment]
I would very much like to contribute PRs for this (and the other issues I've opened), but I need some help with getting up to speed with contributing (e.g. as detailed in #205).

**Comment by mbirkegaard** [comment]
@jfrolich Wrote in #208 
> Interesting. I wonder if you make a conversion that is not always possible if that's not better to be done in the application code.

and I think that could be right. Don't think that changes the problem that we need a directive with a `parse` function that's able to handle errors like in the price example. The argument is laid out very convincingly in @lexi-lambda's excellent [Parse, don't validate](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/)

**Comment by russellmcc** [comment]
My two cents - for me, an invalid custom scalar is a protocol error, just as if the server had sent malformed graphql - I think it should show up to application code the same way.  By the time it gets into application code I don't want to worry that there was some protocol error in my custom fields - just like I don't have to worry about built-in fields like `Float`.  So, I do think that `@ppxCustom` should allow me to indicate that parsing failed, either through `option` or `result`.

**Comment by jfrolich** [comment]
You can parse into an option or result type, just make that part of the type that you are converting to.

**Comment by jfrolich** [comment]
BTW you don't need to implement a serialize function, this is only necessary if you make use of it. You can just return a dummy value and/or throw an exception.
