### ISSUE TITLE
Variables in fragments

### ISSUE THREAD

**Issue by Zimmi48** [reasonml-community/graphql-ppx#211]
The following GraphQL request does not seem to be supported:

```graphql
query getChecks($appId: Int!, $owner: String!, $repo:String!, $base: GitObjectID!, $head: GitObjectID!) {
  repository(name: $repo,owner:$owner) {
    base: object(oid: $base) {
      ... checks
    }
    head: object(oid: $head) {
      ... checks
    }
  }
}

fragment checks on Commit {
  checkSuites(first: 1,filterBy:{appId: $appId}) {
    nodes {
      checkRuns(first: 100) {
        nodes {
          name
          status
          conclusion
        }
      }
    }
  }
}
```

I get two errors: `Variable "$appId" is never used in operation "getChecks"` (first `$appId`) and `Invalid argument. Expected "Int" but received "Null".` (second `$appId`).

I'm using graphql-ppx 1.0.1 in native OCaml, but I doubt this is relevant to this issue.

**Comment by Zimmi48** [comment]
Sorry, I didn't realize that this use case was actually documented in https://beta.graphql-ppx.com/docs/fragment#variables-within-fragments.

Following the documentation, I've changed by request into:

```graphql
fragment checks on Commit @argumentDefinitions(appId: {type: "Int!"}) {
  checkSuites(first: 1,filterBy:{appId: $appId}) {
    nodes {
      checkRuns(first: 100) {
        nodes {
          name
          status
          conclusion
        }
      }
    }
  }
}

query getChecks($appId: Int!, $owner: String!, $repo:String!, $base: GitObjectID!, $head: GitObjectID!) {
  repository(name: $repo,owner:$owner) {
    base: object(oid: $base) {
      ... checks @arguments(appId: $appId)
    }
    head: object(oid: $head) {
      ... checks
    }
  }
}
```

But I still get the second error (`Invalid argument. Expected "Int" but received "Null".`). I'm starting to think that this might actually be related to my use of the native version...

**Comment by jfrolich** [comment]
Yes the native version doesn't support variables in fragments yet. I'd love to upgrade the ReScript version of the PPX to make it work for both native and ReScript.

**Comment by Zimmi48** [comment]
How much of the code base is shared and how much is duplicated between Bucklescript and native ReasonML? Is the evolution of Bucklescript + ReasonML toward ReScript going to make it even harder to share code or not?

**Comment by jfrolich** [comment]
There are now two ppx-es that share code. We can change the ReScript one to also work on native, we "just" need all `Js.*` invocations to be replaced with code that works on native (under a `-native` switch). That's probably a lot less work than updating the current native ppx code.

**Comment by maarekj** [comment]
In my bucklescript code, I have same error: `Invalid argument. Expected "Int" but received "Null"`
It is normal ?

**Comment by a-c-sreedhar-reddy** [comment]
Hi all.
I am also facing the same issue.
How did you fix this?
I am using graphql ppx version 1.0.0
