### ISSUE TITLE
Type Error when using a fragment in another fragment

### ISSUE THREAD

**Issue by kgoggin** [reasonml-community/graphql-ppx#213]
I've got a fragment defined in`OrganizationAvatar.re` like so:

```re
[%graphql
  {|
fragment OrgAvatarFragment on Organization {
  id
  theme {
    id
    primaryColor
    displayName
    logoUrl
  }
}
|}
];
```

Then, in another module:

```re
module AvatarFragment = OrganizationAvatar.OrgAvatarFragment;
[%graphql
  {|
fragment Fragment on Organization {
  website
  ...AvatarFragment
  theme {
    displayName
  }
}
|}
];
```

But I'm getting an error:

```
Error: This expression has type [> `AvatarFragment ]
       but an expression was expected of type [ `OrgAvatarFragment ]
       The second variant type does not allow tag(s) `AvatarFragment
```

Is there some other way I should be referencing the first fragment when creating the second? I'm on v1.0.1 and using the Apollo Client bindings/config settings. Thanks!

**Comment by kgoggin** [comment]
I was able to fix it by giving the aliased module the same name as the fragment. Is that a requirement for aliasing fragments?

**Comment by jfrolich** [comment]
Yes this is a requirement. Because the name in the query need to match the actual fragment name. We are able to leverage the typesystem to show an error if this is not the case.

**Comment by kgoggin** [comment]
Cool, thanks for the clarification. I PR'd an update to the docs to help explain that for anyone else who comes along.
