### ISSUE TITLE
Incompatible type error with 1.0.2-4911e5e.0

### ISSUE THREAD

**Issue by dfalling** [reasonml-community/graphql-ppx#222]
```
  This has type:
    Belt.List.t(TripsQuery.TripsQuery_inner.t_trips) (defined as
      list(TripsQuery.TripsQuery_inner.t_trips))
  Somewhere wanted: list(trip)
  
  The incompatible parts:
    TripsQuery.TripsQuery_inner.t_trips vs
    trip (defined as TripsQuery.t_trips)
```

This worked in `1.0.2-f9af62e.0`, but not in `1.0.1`.  The full source of my component is:

```ocaml
[%graphql
  {|
    query TripsQuery @ppxConfig(
    templateTagImport: "gql",
    templateTagLocation: "@apollo/client",
    templateTagIsFunction: true
  ){
      trips {
        id
        name
      }
    }
  |}
];

type trip = TripsQuery.t_trips;

module TripItem = {
  [@react.component]
  let make = (~trip: trip) => {
    React.string(trip.name);
  };
};

[@react.component]
let make = () => {
  let queryResult = TripsQuery.use();

  let intl = ReactIntl.useIntl();
  let (trips, setTrips) = React.useState(_ => [||]);
  React.useEffect1(
    _ => {
      switch (queryResult.data) {
      | Some({trips}) => setTrips(_ => trips)
      | _ => ()
      };
      None;
    },
    [|queryResult|],
  );

  switch (queryResult, trips) {
  | ({loading: true}, _) => <Loading />
  | ({error: Some(error)}, _) => <div> {React.string(error.message)} </div>
  | (_, trips) =>
    <>
      {trips
       |> Array.map(trip => <TripItem trip key={trip.id} />)
       |> ReasonReact.array}
    </>
  };
};
```

And the error's happening on the `|> Array.map(...` line near the bottom.

**Comment by jfrolich** [comment]
You say it broke in `1.0.1` and works in `1.0.2-f9af62e.0`, but the latter is a newer development version. Does that mean it is something that has been fixed in the newest version?

**Comment by dfalling** [comment]
Sorry, I explained that poorly.  Using that root type `t_trips` never worked until `1.0.2-x`.  Before I had to use that internal type of `TripsQuery_inner.t_trips`.  So `1.0.2-4911e5e.0` is a regression for me to the behavior in `1.0.1`.

**Comment by jfrolich** [comment]
@dfalling: The root type should be the type that is exposed. The reason that `TripsQuery_inner.t_trips` is there is because of the extension of the query module. We constrained the type to much in `1.0.0` so using `TripsQuery.t_trips` wouldn't work when you used the hook, which was fixed in `1.0.1`. Why is this a regression for you?

**Comment by jfrolich** [comment]
Are you sure this is a bug in `1.0.1`? Because we use this pattern a lot in `1.0.1` and there are no problems.

**Comment by jfrolich** [comment]
Can you remove the node modules and run `npm install` again. Sometimes an old version of the ppx is stuck.

**Comment by dfalling** [comment]
Yes, this happens with a fresh build.

And sorry, I forgot why I bumped versions. This worked in `1.0.1` and in `1.0.2-f9af62e.0`. I moved to 1.0.2 for the `templateTagIsFunction`.

**Comment by dfalling** [comment]
I just retried with `1.0.2-f9af62e.0` and have the same problem.  I'm not sure how it was working properly with `templateTagIsFunction` and `t_trips` before, but now I can't get both working at the same time with any version of `1.0.2`.  If I switch to `TripsQuery_inner.t_trips` everything works as expected.

**Comment by jfrolich** [comment]
The diff (f9af62e...4911e5e) just added the template tag as string option so I am confused as to why you have this module type problem. Can you try `1.0.2-b5c3318.0` because that one fixes an issue with upgrading the ppx (in the postinstall script).

**Comment by dfalling** [comment]
`1.0.2-b5c3318.0` works for me!  Thanks!
