### ISSUE TITLE
verifyArgsAndParse type is undocumented

### ISSUE THREAD

**Issue by Kingdutch** [reasonml-community/graphql-ppx#231]
I'm trying to create a fragment in a module and expose the fragment with a React component in the module file while hiding the other details in the module. However, upon using the fragment the compiler throws the error `The value verifyArgsAndParse can't be found in Conversation_View` which is true since [the definition I copied from the docs](https://beta.graphql-ppx.com/docs/definition/) does not expose such a function (even though it appears to be required).

I have the following fragment definition
```rescript
module Conversation_View = %graphql(`
  fragment Conversation_View on Conversation @argumentDefinitions(lastMessages: { type: "Int!" }) {
      id
      ...Conversation_Header
      messages(last: $lastMessages) {
        pageInfo {
          hasPreviousPage
          hasNextPage
          startCursor
          endCursor
        }
        nodes {
          id
          ...Chat_Message
        }
      }
  }
`)
```

This is used in the following snippet in a different module.
```graphql
  mutation createPrivateConversation($participant: ID!) {
    createPrivateConversation(input: {
      participant: $participant
    }) {
      errors
      conversation {
        ...Conversation_View @arguments(lastMessages: 20)
      }
    }
  }
```

**Comment by jfrolich** [comment]
It's an internal function that is called when parsing the fragment (and type checking the arguments). It needs to be exposed because it's being called in a query module when you use a fragment. You can actually use the `%graphql("...")` in interface files as well (just like the react ppx). It's not a great idea to write the interface yourself because if you need the fragment you probably also need the full record types available (and it is a lot of work to type them manually in an interface file :)).

**Comment by Kingdutch** [comment]
It looks like I was doing something wrong, not sure where I made the typo. I now have it working :D 

For possible documentation improvements there were a few things that tripped me up of which I'm not entirely clear why they are the way they are:

- Usage of fragments in a `res` file require a module alias to work. Using the dot in the fragment spread trips up the naming of the fragment variable causing a compile error it seems. (See Error 1)
- Conversely a module alias is not easily created in an interface (`resi`) file but is also not needed there, the Module.Fragment name works fine there.
- I was able to add arguments but the `@arguments` directive seems not to accept static arguments, only variables that are also available in the query. (See Error 2)

<details><summary>Error 1</summary>
<p>
This is the error shown when using a fully namespaced fragment in a `.res` file.

```
   8 ┆ __typename
   9 ┆ id
  10 ┆ ...ConversationHeader.Conversation_Header
  11 ┆ messages(last: $messagesLast) {
  12 ┆   pageInfo {
  
  This has type: [> #\"ConversationHeader.Conversation_Header"]
  Somewhere wanted: [#Conversation_Header]
  The second variant type does not allow tag(s)
  `ConversationHeader.Conversation_Header
```
</p>
</details>


<details><summary>Error 2</summary>
<p>


```
  19 ┆     __typename
  20 ┆     id
  21 ┆     ...Conversation_View @arguments(messagesLast: 20)
  22 ┆   }
  23 ┆ }
  
  This call is missing an argument of type (~messagesLast: [#NonNull_Int])
```
</p>
</details>

<details><summary>For anyone else who may run into similar issues I've included a compiling example below.</summary>
<p>
The implementation file, aliasing the fragments and using the newly created fragment for a query in this file.

Conversation.res
```rescript
module Chat_Message = ChatMessage.Chat_Message;
module Conversation_Header = ConversationHeader.Conversation_Header;

module Conversation_View = %graphql(`
  fragment Conversation_View on Conversation @argumentDefinitions(messagesLast: { type: "Int!" }) {
    __typename
    id
    ...Conversation_Header
    messages(last: $messagesLast) {
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
      nodes {
        id
        ...Chat_Message
      }
    }
  }
`)

module GetConversationMessages = %graphql(`
  query conversation_messages($id: ID!, $messagesLast: Int!) {
    conversation(id: $id) {
      ...Conversation_View @arguments(messagesLast: $messagesLast)
    }
  }
`)
```

The interface file exposes only the fragment for use by others (and a React component not shown here).

Conversation.resi
```rescript
module Conversation_View : %graphql(`
  fragment Conversation_View on Conversation @argumentDefinitions(messagesLast: { type: "Int!" }) {
    __typename
    id
    ...ConversationHeader.Conversation_Header
    messages(last: $messagesLast) {
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
      nodes {
        id
        ...ChatMessage.Chat_Message
      }
    }
  }
`)
```

Another file is now also able to use the fragment.

OtherComponent.res
```rescript
module Conversation_View = Conversation.Conversation_View;

module CreatePrivateConversation = %graphql(`
  mutation createPrivateConversation($participant: ID!) {
    createPrivateConversation(input: {
      participant: $participant
    }) {
      errors
      conversation {
        __typename
        id
        ...Conversation_View @arguments(messagesLast: 20)
      }
    }
  }
`)
```
</p>
</details>

**Comment by jfrolich** [comment]
> It looks like I was doing something wrong, not sure where I made the typo. I now have it working :D
> 
> For possible documentation improvements there were a few things that tripped me up of which I'm not entirely clear why they are the way they are:
> 
> * Usage of fragments in a `res` file require a module alias to work. Using the dot in the fragment spread trips up the naming of the fragment variable causing a compile error it seems. (See Error 1)

Yes, dots in fragments are not valid GraphQL syntax, so we cannot include them without breaking editor plugins that rely on the GraphQL syntax.

> * Conversely a module alias is not easily created in an interface (`resi`) file but is also not needed there, the Module.Fragment name works fine there.

Hmm you should be able to alias modules in an interface. If you don't want to expose them you can use `open`.

> * I was able to add arguments but the `@arguments` directive seems not to accept static arguments, only variables that are also available in the query. (See Error 2)


Yep, the `@arguments` is more of a hint to the GraphQL compiler (you cannot rename variables as well). This is mainly because these features are not available on Apollo etc. AFAIK (the relay compiler does some magic to make these things possible).

**Comment by jfrolich** [comment]
It would be great to document some of these better. I happily accept any PR to the docs.
