### ISSUE TITLE
Not supported on darwin arm64

### ISSUE THREAD

**Issue by bbqsrc** [reasonml-community/graphql-ppx#232]
```
graphql-ppx does not support this platform :(

graphql-ppx comes prepacked as built binaries to avoid large
dependencies at build-time.

If you want graphql-ppx to support this platform natively,
please open an issue at our repository, linked above. Please
specify that you are on the darwin platform,
on the arm64 architecture.
```
🙂

**Comment by jfrolich** [comment]
Oh yes we should support it. We just have to figure out how to compile it on github actions. Any idea?

**Comment by bbqsrc** [comment]
From furious Googling, and seeing you don't use xcodebuild anywhere directly, I suppose something here might help: https://discuss.ocaml.org/t/ann-easy-cross-compilation-using-esy/6612

**Comment by jfrolich** [comment]
I think cross-compilation is available in the latest point release of 4.10. (the example above is for cross-compile to mobile).

**Comment by jfrolich** [comment]
BTW with Rosetta we could probably just run the intel version for now. So maybe you can edit the detection script and allow mac-os arm? That will probably work. If it works a PR is welcome!

**Comment by bbqsrc** [comment]
Yes, with Rosetta it will definitely also work. I will try that later and if it does send a PR. :)

**Comment by jfrolich** [comment]
https://github.com/reasonml-community/graphql-ppx/blob/master/copyPlatformBinaryInPlace.js

**Comment by jfrolich** [comment]
> Yes, with Rosetta it will definitely also work. I will try that later and if it does send a PR. :) Also the performance of Rosetta is ridiculously good, I'm still amazed lol.

Cool, I am tempted to sell my 16" maxed out mbp for a M1 Air lol :D

**Comment by bbqsrc** [comment]
I did get the Air, just to really test it. 12 core Ryzen 5 vs MacBook on an intense Rust release build and the air was only 20% slower... whereas my last generation 15in MacBook Pro is about twice as slow as the Air. And it never gets warmer than 80%! Just unbelievable stuff, especially since I am not a big fan of Apple, heh.

**Comment by ManasJayanth** [comment]
@jfrolich Maybe for MacOS arm64 users the ppx could build from source?

**Comment by ManasJayanth** [comment]
I recall some other PPX doing this (cant recall)
