### ISSUE TITLE
Can't parse graphql response in Rescript

### ISSUE THREAD

**Issue by fatpig0416** [reasonml-community/graphql-ppx#239]
I getting response via graphqlppx-RoR.
But I got error which is saying type mismatch.

Response has type Js.Promise.t<Js.t<{... blah blah}>>
But somewhere wanted Js.Promise.t<{blah blah}>
![image](https://user-images.githubusercontent.com/38931218/106260969-feb8c500-625b-11eb-8e5c-25efcd12ebd0.png)

Hope anybody helps me out.

Best regards.

**Comment by idkjs** [comment]
@fatpig0416 what is `graphqlppx-RoR`?
