### ISSUE TITLE
pollInterval None should cancel polling?

### ISSUE THREAD

**Issue by AlexMoutonNoble** [reasonml-community/graphql-ppx#248]
Hi folks.
I have been using react state to gate pollInterval on some queries, as some tasks progress on the back end.  It took me a while to figure that None does not cancel a set interval.  Should it? It seems like it should?

Seems likely a one liner.  I can take a look if youre interested in a PR.

Thanks
Alex

**Comment by jfrolich** [comment]
you probably want to file an issue in https://github.com/reasonml-community/rescript-apollo-client

**Comment by AlexMoutonNoble** [comment]
ah yep! thanks
