### ISSUE TITLE
Syntax error in directives documentation

### ISSUE THREAD

**Issue by Pet3ris** [reasonml-community/graphql-ppx#253]
Hi There,

I'm looking at the mutually recursive module example within the directives documentation (https://github.com/reasonml-community/graphql-ppx/blob/855b16bca8621ae5f0a1179edc8bf46061248e8b/documentation/docs/directives.md).

I tried to paste it in the ReScript playground and the syntax doesn't convert/compile: https://rescript-lang.org/try?ext=re&code=LYewJgrgNgpgBAVQM4wE4EUJoJ5wLxwDaApAOaoCGADgBYCOUcA3gD4BQccdWquTHnOBBSo4AASpUAHgGFhAFxDAAFKEiwAXHABEyNNoCUzAYLgBLMCcEA7CsBhWAvgOdwWjuBWthEIrf0F5bCp4eXxjUzhbewBBbwBJMC0keVQza1ITRwBuE1gwqgpUFC09DB5sADp5AH1hNHwAPjh5XMF8uBEzCigzAC8YLTC8ZrLMHGq6kTaPAgDOIJCW8PmbOxg4sETk1PTMwRy8mAKilHD60RGI02iNhKTOgHczeQBjGjhlC8rbo1XTAByIGs8Cu2iBt20cAA1NChCJKhYrIIAMpKGDKX5NKLrGFw75IyKuTiHOCOIA

**Comment by jfrolich** [comment]
This is primarily because the ppx is not running in the playground
