### ISSUE TITLE
custom-fields isn't working from bs-config as expected

### ISSUE THREAD

**Issue by JasoonS** [reasonml-community/graphql-ppx#258]
using isn't creating custom fields for me. It was working on some other code bases, but I can't get it to work now.
```json
  "graphql": {
    //... other config ...
    "custom-fields": {
      "BigInt": "BigInt",
      "Bytes": "Bytes"
    },
  },
  ```
  
I still need to manually add `@ppxCustom(module: "BigInt")` to get it to work.

**Comment by jfrolich** [comment]
Did you try camelcase (`customFields`)? The kebab-case was used before all configuration was made consistent in 1.0 I think.

**Comment by JasoonS** [comment]
Hi @jfrolich , thank you so much for the response. I worked out the issue, it is thankfully very simple, just not user friendly.

It seems like the config you give to the ppx in the `"graphql"` section of the bsconfig cannot have trailing commas.

It would be a nice fix to give a reasonable error message if someone leaves a trailing comma in their graphql config

**Comment by jfrolich** [comment]
> It seems like the config you give to the ppx in the `"graphql"` section of the bsconfig cannot have trailing commas.

AH! Thanks! I was planning to incorporate the custom JSON parsing library that ReScript uses in `graphql-ppx` for performance reasons. But this also seems like a good reason.

**Comment by JasoonS** [comment]
Amazing!
