### ISSUE TITLE
Remove `yarn.lock` file from repository

### ISSUE THREAD

**Issue by Kingdutch** [reasonml-community/graphql-ppx#260]
The repository contains both a `package-lock.json` and `yarn.lock` file. These files are not used by packages requiring graphql-ppx but only by contributors. The [contributing guidelines](https://beta.graphql-ppx.com/docs/contributing/) tell us to use `npm install`.

When using `yarn install` it produces the following warning.

> package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

To be clearer to contributors, avoid the error that yarn points to and match the contributing guidelines it makes sense to remove `yarn.lock` and standardise on npm for development.

**Comment by jfrolich** [comment]
Sounds like a great idea. PR welcome, if you want to contribute it.
