### ISSUE TITLE
Unable to install v1.2.1

### ISSUE THREAD

**Issue by dfalling** [reasonml-community/graphql-ppx#264]
v1.2.1 is failing to install for me:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@reasonml-community/graphql-ppx/-/graphql-ppx-1.2.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/ido/ido/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This happens locally and in CI. My package.json is requesting `"@reasonml-community/graphql-ppx": "1.2.1",`

**Comment by jfrolich** [comment]
Same here. There was an error on the CI while publishing, so maybe it was partly published. Will try to release as `1.2.2`. There are not much updates, so you can also try `1.2.0`.

**Comment by jfrolich** [comment]
Just tested `1.2.2` and it works now (not sure what went wrong, maybe a npm glitch?)!

**Comment by dfalling** [comment]
`1.2.2` fixed it for me, thanks!
