### ISSUE TITLE
 Error while running external preprocessor - is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by LukasDeco** [reasonml-community/graphql-ppx#275]
Command line: C:\Users\Owner\Lukas Projects\occasionally-for-business\realm-app\hosting\node_modules\@reasonml-community\graphql-ppx\ppx "C:\Users\Owner\AppData\Local\Temp\ppx6589c0Process.res" "C:\Users\Owner\AppData\Local\Temp\ppx5cfb70Process.res"

rescript: [18/51] src/bindings/Next.ast
FAILED: src/bindings/Next.ast
'C:\Users\Owner\Lukas' is not recognized as an internal or external command,
operable program or batch file.

I'm on a windows 10 if that helps. Using version 1.2.2.

**Comment by illusionalsagacity** [comment]
> C:\Users\Owner\Lukas Projects\occasionally-for-business\realm-app\hosting\node_modules@reasonml-community\graphql-ppx\ppx "C:\Users\Owner\AppData\Local\Temp\ppx6589c0Process.res"

looks like your folder `Lukas Projects` is not escaped. try renaming the folder to a unix-valid name like `Lukas_Projects`?

**Comment by LukasDeco** [comment]
Sup dude. You are right. Nice spot.
I am running WSL now so luckily this isn't a problem anymore. Thanks for the eye though!
