### ISSUE TITLE
Add INPUT_OBJECT example

### ISSUE THREAD

**Issue by nirvdrum** [reasonml-community/graphql-ppx#66]
Instead of having a bunch of mutations handling a single field update, I thought I'd look at how graphql_ppx_re handles `INPUT_OBJECT`. The expected type for my input field is pretty gnarly: a closed object with every field being an `option`. Constructing such an object is not going to be pretty, so I thought I'd see if there were generated helper functions that I overlooked. Unfortunately, I couldn't find any examples of how one would use an `INPUT_OBJECT` in the documentation. I tried digging through the source and didn't find anything there, either. I think adding an example to the README would be very helpful.

**Comment by baransu** [comment]
It would be good to add it into README as you pointed 🙂 

Unfortunately, there are no helper functions for that. You have to create a Js.t object and pass it as a query argument to your mutation. It's quite simple but can create a lot of boilerplate.

**Comment by jfrolich** [comment]
It pretty good, just create an object with the object syntax with the values wrapped in Some. A concern for me is that it's an open object at the moment, so it allows fields that are not available.

**Comment by baransu** [comment]
@jfrolich It should improve when we migrate to records 🙂 We can probably think about generating functions for that. It would allow passing None in a case where the input object has a lot of optional fields.

**Comment by jfrolich** [comment]
> @jfrolich It should improve when we migrate to records 🙂 

Yeah that was my initial thought as well!

> We can probably think about generating functions for that. It would allow passing None in a case where the input object has a lot of optional fields.

Agree. I think it can even be done with adding bs.deriving abstract on the record type.

**Comment by jfrolich** [comment]
Should be covered in the new documentation, closing for now. Reopen if this has not been addressed.

**Comment by nirvdrum** [comment]
Where can I find the new documentation? I didn't see anything in _master_.

**Comment by jfrolich** [comment]
In the 1.0 branch. It has not been written yet so let's reopen this :D
