### ISSUE TITLE
Release under reasonml-community on npm

### ISSUE THREAD

**Issue by baransu** [reasonml-community/graphql-ppx#85]
Right now we're releasing under `@baransu/graphql_ppx`. As we're in the `@reasonml-community` organization it would be great to release in the same org on npm or some other organization with high credibility like `@reason/graphql_ppx`.

I would like this to take effect from the upcoming 1.0 release.

/cc @ryyppy @anmonteiro

**Comment by anmonteiro** [comment]
I'm not sure who has access to the `@reasonml-community` scope on NPM, but I think that could be a viable solution.
