### ISSUE TITLE
Support interfaces with a combination of fields and type spreads

### ISSUE THREAD

**Issue by jfrolich** [reasonml-community/graphql-ppx#92]
As per the spec

https://graphql.org/learn/schema/#interfaces

```
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name
    ... on Droid {
      primaryFunction
    }
  }
}
```

**Comment by jfrolich** [comment]
Potential solution, keep current implementation if no interface fields are selected outside of the spreads. But if they are provided, wrap the result in a records that contains the fields with potentially a `types` fields that contains the union spreads (if they are provided).

**Comment by jfrolich** [comment]
Moving this to 1.1 so it will not be a blocker. Doing this is probably a bit tricky to implement well.

**Comment by jfrolich** [comment]
I implemented the whole shebang in #173. It would be great if anyone that actually uses interface can help me test it in a real-world situation. (We want to use it to adopt the node query, but we don't have it yet).

**Comment by amsross** [comment]
@jfrolich can I refer you to #168? The example query and snapshotted API code is a distillation of a real-world use-case I was working on.

**Comment by jfrolich** [comment]
Can you try with the PR? There is a dev release on npm with the commit hash
